# Workflow for building and deploying only the apps/landing-page Astro site to GitHub Pages using Bun
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Landing Page to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "apps/landing-page" # Set to the subfolder where the landing page is located

jobs:
  build:
    name: Build Landing Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1 # Official Bun setup action
        with:
          bun-version: "latest" # Specify the version of Bun you want to use
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Install dependencies with Bun
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro using Bun
        run: bun astro build \
          --site "${{ steps.pages.outputs.origin }}" \
          --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy Landing Page
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
