name: Build and Deploy with Bun
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install and Build Astro Site
        run: |
          cd landing
          bun install
          bun run build
          cd ..

      - name: Install and Build React App
        run: |
          cd app
          bun install
          bun run build
          cd ..

      - name: Prepare deployment
        run: |
          mkdir deploy
          cp -r landing/dist/* deploy/
          mkdir -p deploy/app
          cp -r app/dist/* deploy/app/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
